# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

# 1D and 2D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Built-in creation functions
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 2)))
print("Arange:", np.arange(1, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))
print("Identity Matrix:\n", np.eye(3))

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Arange: [1 3 5 7 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Indexing and Slicing

In [2]:
# 1D Indexing & Slicing
arr = np.array([10, 20, 30, 40, 50, 60])
print("First element:", arr[0])
print("Elements from index 1 to 4:", arr[1:5])
print("Every 2nd element:", arr[::2])

# 2D Indexing & Slicing
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nMatrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First two rows, first two columns:\n", matrix[0:2, 0:2])
print("All rows, column 1:", matrix[:, 1])

First element: 10
Elements from index 1 to 4: [20 30 40 50]
Every 2nd element: [10 30 50]

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First two rows, first two columns:
 [[10 20]
 [40 50]]
All rows, column 1: [20 50 80]


### 3. Reshaping and Flattening

In [3]:
a = np.arange(1, 13)
print("Original 1D array:", a)

# Reshape to (3, 4)
reshaped = a.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Flatten back to 1D
print("Flattened array:", reshaped.flatten())

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


### 4. Array Broadcasting

In [4]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])

print("Matrix:\n", mat)
print("Row vector:", row)
print("Broadcasted Addition (mat + row):\n", mat + row)
print("Scalar Multiplication (mat * 2):\n", mat * 2)

Matrix:
 [[1 2 3]
 [4 5 6]]
Row vector: [10 20 30]
Broadcasted Addition (mat + row):
 [[11 22 33]
 [14 25 36]]
Scalar Multiplication (mat * 2):
 [[ 2  4  6]
 [ 8 10 12]]


### 5. Mathematical and Statistical Operations

In [5]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("Element-wise Addition:\n", x + y)
print("Element-wise Multiplication:\n", x * y)
print("Matrix Multiplication (Dot Product):\n", np.dot(x, y))

# Summary stats
print("\nSum of all elements:", x.sum())
print("Column-wise sum:", x.sum(axis=0))
print("Row-wise sum:", x.sum(axis=1))
print("Mean:", x.mean())
print("Standard Deviation:", round(x.std(), 2))
print("Square root of x:\n", np.sqrt(x))

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication (Dot Product):
 [[19 22]
 [43 50]]

Sum of all elements: 10
Column-wise sum: [4 6]
Row-wise sum: [3 7]
Mean: 2.5
Standard Deviation: 1.12
Square root of x:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
